### PR TITLE
do nothing if orientation cannot be determined

### PR DESCRIPTION
**Pull request by monsieurchico**
Linked to issue : 
https://github.com/JellyBellyDev/ImageOrientationFix/issues/1

### CODE REVIEW

**Comment by JellyBellyDev** [comment]
Thank you so much. good job!

**Comment by monsieurchico** [comment]
Thanks you, your project is great !

**Comment by JellyBellyDev** [comment]
then add a star!
thank you! :P

**Comment by monsieurchico** [comment]
just did ^^! can you update packagist ?

**Comment by JellyBellyDev** [comment]
thank you!
You had to update yourself.
I found out why it did not: I mistakenly set the version option in the composer.json :S
Now is ok! ;)

**Pull request merged**
